CREATE TABLE gift_rating (
  id VARCHAR(36) PRIMARY KEY,
  gift_id VARCHAR(36) NOT NULL UNIQUE,
  stars INT NOT NULL,
  comment VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rating_gift FOREIGN KEY (gift_id) REFERENCES gift(id)
);
