ALTER TABLE gift ADD COLUMN access_pin_hash VARCHAR(100) NULL;
ALTER TABLE gift ADD COLUMN max_open_count INT NOT NULL DEFAULT 0;
ALTER TABLE gift ADD COLUMN open_count INT NOT NULL DEFAULT 0;
ALTER TABLE gift ADD COLUMN current_step INT NOT NULL DEFAULT 0;
ALTER TABLE gift ADD COLUMN total_steps INT NOT NULL DEFAULT 0;
