"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { authHeaders, currentFirebaseUser, signInWithFirebase, signOutFirebase } from "./authClient";

const api=process.env.NEXT_PUBLIC_API_URL||"https://backend-production-22bd.up.railway.app";
type Overview={users:number;gifts:number;orders:number;paidOrders:number;revenuePaise:number;responses:number;activeCoupons:number;integrations:{firebase:boolean;groq:boolean;razorpay:boolean}};
type Coupon={id:string;code:string;discountType:"PERCENT"|"FIXED";discountValue:number;maxDiscountPaise:number|null;minOrderPaise:number;usageLimit:number|null;usedCount:number;validFrom:string|null;expiresAt:string|null;active:boolean};
type Activity={id:string;name:string;description:string;pricePaise:number;active:boolean};
type Bundle={id:string;name:string;description:string;pricePaise:number;activityIds:string;recipientType:"Lover"|"Friend"|"Parents"|"Sibling"|"Other";active:boolean};
type Gift={id:string;title:string;recipientName:string;occasion:string;status:string;totalPaise:number;updatedAt:string};
type Order={id:string;giftId:string;amountPaise:number;discountPaise:number;couponCode:string|null;status:string;providerOrderId:string;createdAt:string};
type User={id:string;email:string;displayName:string;role:string;createdAt:string};
type Tab="overview"|"coupons"|"activities"|"bundles"|"gifts"|"orders"|"users"|"settings";
type CouponForm={code:string;discountType:"PERCENT"|"FIXED";discountValue:number;maxDiscountPaise:string;minOrderPaise:string;usageLimit:string;expiresAt:string;active:boolean};
const emptyCoupon:CouponForm={code:"",discountType:"PERCENT",discountValue:10,maxDiscountPaise:"",minOrderPaise:"0",usageLimit:"",expiresAt:"",active:true};

async function request<T>(path:string,options:RequestInit={}):Promise<T>{
  const auth=await authHeaders("local-admin");
  const response=await fetch(`${api}${path}`,{...options,headers:{...auth,...(options.body?{"Content-Type":"application/json"}:{}),...(options.headers||{})}});
  if(!response.ok){const error=new Error(response.status===403?"ADMIN_REQUIRED":"REQUEST_FAILED");(error as Error&{status?:number}).status=response.status;throw error}
  if(response.status===204||response.headers.get("content-length")==="0")return undefined as T;
  return response.json();
}

export function AdminPanel({onExit}:{onExit:()=>void}){
  const [authState,setAuthState]=useState<"checking"|"signed-out"|"ready"|"forbidden">("checking");
  const [profile,setProfile]=useState<{email?:string|null;displayName?:string|null}>({});
  const [tab,setTab]=useState<Tab>("overview");
  const [overview,setOverview]=useState<Overview|null>(null);const [coupons,setCoupons]=useState<Coupon[]>([]);const [activities,setActivities]=useState<Activity[]>([]);const [bundles,setBundles]=useState<Bundle[]>([]);const [gifts,setGifts]=useState<Gift[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [users,setUsers]=useState<User[]>([]);
  const [loading,setLoading]=useState(false);const [notice,setNotice]=useState("");const [couponForm,setCouponForm]=useState(emptyCoupon);

  const load=useCallback(async()=>{
    setLoading(true);setNotice("");
    try{
      const [summary,couponRows,activityRows,bundleRows,giftRows,orderRows,userRows]=await Promise.all([
        request<Overview>("/api/admin/overview"),request<Coupon[]>("/api/admin/coupons"),request<Activity[]>("/api/admin/activities"),request<Bundle[]>("/api/admin/bundles"),request<Gift[]>("/api/admin/gifts"),request<Order[]>("/api/admin/orders"),request<User[]>("/api/admin/users")
      ]);
      setOverview(summary);setCoupons(couponRows);setActivities(activityRows);setBundles(bundleRows);setGifts(giftRows);setOrders(orderRows);setUsers(userRows);setAuthState("ready");
    }catch(error){setAuthState((error as Error).message==="ADMIN_REQUIRED"?"forbidden":"signed-out")}
    finally{setLoading(false)}
  },[]);

  useEffect(()=>{void currentFirebaseUser().then(user=>{if(!user){setAuthState("signed-out");return}setProfile(user);void load()}).catch(()=>setAuthState("signed-out"))},[load]);
  async function login(){setLoading(true);setNotice("");try{const user=await signInWithFirebase("google");setProfile(user);const headers=await authHeaders("local-admin");await fetch(`${api}/api/auth/session`,{method:"POST",headers});await load()}catch{setNotice("Google sign-in did not finish. Check the Firebase authorized domain and try again.");setAuthState("signed-out")}finally{setLoading(false)}}
  async function logout(){await signOutFirebase();setAuthState("signed-out");setOverview(null)}
  async function createCoupon(){
    setLoading(true);setNotice("");
    try{
      const body={code:couponForm.code,discountType:couponForm.discountType,discountValue:couponForm.discountType==="FIXED"?Number(couponForm.discountValue)*100:Number(couponForm.discountValue),maxDiscountPaise:couponForm.maxDiscountPaise?Number(couponForm.maxDiscountPaise)*100:null,minOrderPaise:Number(couponForm.minOrderPaise||0)*100,usageLimit:couponForm.usageLimit?Number(couponForm.usageLimit):null,validFrom:null,expiresAt:couponForm.expiresAt?new Date(couponForm.expiresAt).toISOString():null,active:couponForm.active};
      await request("/api/admin/coupons",{method:"POST",body:JSON.stringify(body)});setCouponForm(emptyCoupon);setNotice("Coupon created.");await load();
    }catch{setNotice("Coupon could not be created. Check that its code is unique.")}finally{setLoading(false)}
  }
  async function saveCoupon(coupon:Coupon,patch:Partial<Coupon>={}){
    const next={...coupon,...patch};await request(`/api/admin/coupons/${coupon.id}`,{method:"PUT",body:JSON.stringify({code:next.code,discountType:next.discountType,discountValue:next.discountValue,maxDiscountPaise:next.maxDiscountPaise,minOrderPaise:next.minOrderPaise,usageLimit:next.usageLimit,validFrom:next.validFrom,expiresAt:next.expiresAt,active:next.active})});await load();
  }
  async function saveActivity(activity:Activity){await request(`/api/admin/activities/${activity.id}`,{method:"PUT",body:JSON.stringify(activity)});setNotice(`${activity.name} updated.`);await load()}
  async function saveBundle(bundle:Bundle){await request(`/api/admin/bundles/${bundle.id}`,{method:"PUT",body:JSON.stringify(bundle)});setNotice(`${bundle.name} updated.`);await load()}
  async function updateRole(user:User,role:string){await request(`/api/admin/users/${user.id}/role`,{method:"PUT",body:JSON.stringify({role})});await load()}
  const nav=useMemo(()=>[{id:"overview",icon:"⌂",label:"Overview"},{id:"coupons",icon:"%",label:"Coupons"},{id:"activities",icon:"✦",label:"Blocks & pricing"},{id:"bundles",icon:"▦",label:"Bundles"},{id:"gifts",icon:"♡",label:"Gifts"},{id:"orders",icon:"₹",label:"Orders"},{id:"users",icon:"◎",label:"Users"},{id:"settings",icon:"⚙",label:"Integrations"}] as {id:Tab;icon:string;label:string}[],[]);

  if(authState==="checking")return <main className="admin-auth"><span>♡</span><p>Opening your control room…</p></main>;
  if(authState==="signed-out")return <main className="admin-auth"><section><button className="brand" onClick={onExit}><span className="brand-heart">♥</span> mypookie.</button><i>⚙</i><small>PRIVATE OPERATIONS CONSOLE</small><h1>Everything behind the magic.</h1><p>Sign in with the approved administrator account to manage pricing, coupons, gifts, payments and integrations.</p><button className="admin-google" disabled={loading} onClick={login}><b>G</b>{loading?"Connecting securely…":"Continue with Google"}</button>{notice&&<output>{notice}</output>}<button className="admin-back" onClick={onExit}>← Return to mypookie.</button></section></main>;
  if(authState==="forbidden")return <main className="admin-auth"><section><button className="brand" onClick={onExit}><span className="brand-heart">♥</span> mypookie.</button><i>⌁</i><small>ACCESS LIMITED</small><h1>This account is not an admin.</h1><p>{profile.email} is signed in, but it is not on the administrator allowlist.</p><button className="admin-google" onClick={logout}>Sign out and use another account</button><button className="admin-back" onClick={onExit}>← Return to mypookie.</button></section></main>;

  return <main className="admin-shell">
    <aside className="admin-sidebar"><button className="brand" onClick={onExit}><span className="brand-heart">♥</span> mypookie.</button><small>ADMIN CONSOLE</small><nav>{nav.map(item=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="admin-profile"><b>{(profile.displayName||profile.email||"A").charAt(0).toUpperCase()}</b><span><strong>{profile.displayName||"Administrator"}</strong><small>{profile.email}</small></span><button onClick={logout}>↗</button></div></aside>
    <section className="admin-workspace"><header><div><small>MYPOOKIE OPERATIONS</small><h1>{nav.find(item=>item.id===tab)?.label}</h1></div><div><button onClick={()=>void load()}>{loading?"Refreshing…":"↻ Refresh"}</button><button className="admin-view-site" onClick={onExit}>View site ↗</button></div></header>{notice&&<div className="admin-notice">{notice}</div>}
      {tab==="overview"&&overview&&<AdminOverview data={overview} gifts={gifts.slice(0,5)} orders={orders.slice(0,5)}/>}
      {tab==="coupons"&&<section className="admin-section"><div className="admin-section-head"><div><small>DISCOUNTS</small><h2>Coupon control</h2><p>Create codes without touching checkout code.</p></div></div><div className="coupon-create"><label>Code<input value={couponForm.code} onChange={event=>setCouponForm({...couponForm,code:event.target.value.toUpperCase()})} placeholder="POOKIE20"/></label><label>Type<select value={couponForm.discountType} onChange={event=>setCouponForm({...couponForm,discountType:event.target.value as "PERCENT"|"FIXED"})}><option value="PERCENT">Percentage</option><option value="FIXED">Fixed ₹</option></select></label><label>Value<input type="number" min="1" value={couponForm.discountValue} onChange={event=>setCouponForm({...couponForm,discountValue:Number(event.target.value)})}/></label><label>Minimum ₹<input type="number" min="0" value={couponForm.minOrderPaise} onChange={event=>setCouponForm({...couponForm,minOrderPaise:event.target.value})}/></label><label>Usage limit<input type="number" min="1" value={couponForm.usageLimit} onChange={event=>setCouponForm({...couponForm,usageLimit:event.target.value})} placeholder="Unlimited"/></label><label>Expires<input type="datetime-local" value={couponForm.expiresAt} onChange={event=>setCouponForm({...couponForm,expiresAt:event.target.value})}/></label><button disabled={!couponForm.code||loading} onClick={createCoupon}>＋ Create coupon</button></div><div className="admin-table"><div className="admin-table-row heading"><span>Code</span><span>Offer</span><span>Usage</span><span>Status</span><span>Action</span></div>{coupons.map(coupon=><div className="admin-table-row" key={coupon.id}><strong>{coupon.code}</strong><span>{coupon.discountType==="PERCENT"?`${coupon.discountValue}%`:`₹${coupon.discountValue/100}`}</span><span>{coupon.usedCount}{coupon.usageLimit?` / ${coupon.usageLimit}`:" · unlimited"}</span><span className={coupon.active?"status-live":"status-off"}>{coupon.active?"Active":"Disabled"}</span><button onClick={()=>saveCoupon(coupon,{active:!coupon.active})}>{coupon.active?"Disable":"Enable"}</button></div>)}</div></section>}
      {tab==="activities"&&<section className="admin-section"><div className="admin-section-head"><div><small>CATALOG</small><h2>Blocks and pricing</h2><p>Changes affect every new gift and server-calculated checkout.</p></div></div><div className="admin-card-grid">{activities.map(activity=><article className="admin-edit-card" key={activity.id}><div><span>✦</span><label className="admin-switch"><input type="checkbox" checked={activity.active} onChange={event=>setActivities(current=>current.map(item=>item.id===activity.id?{...item,active:event.target.checked}:item))}/><i/></label></div><input className="admin-title-input" value={activity.name} onChange={event=>setActivities(current=>current.map(item=>item.id===activity.id?{...item,name:event.target.value}:item))}/><textarea value={activity.description} onChange={event=>setActivities(current=>current.map(item=>item.id===activity.id?{...item,description:event.target.value}:item))}/><label>Price ₹<input type="number" value={activity.pricePaise/100} onChange={event=>setActivities(current=>current.map(item=>item.id===activity.id?{...item,pricePaise:Number(event.target.value)*100}:item))}/></label><button onClick={()=>saveActivity(activity)}>Save block</button></article>)}</div></section>}
      {tab==="bundles"&&<section className="admin-section"><div className="admin-section-head"><div><small>PACKAGES</small><h2>Bundle manager</h2><p>Control every recipient-specific experience and its price.</p></div></div><div className="admin-card-grid bundles">{bundles.map(bundle=><article className="admin-edit-card" key={bundle.id}><div><span>▦</span><label className="admin-switch"><input type="checkbox" checked={bundle.active} onChange={event=>setBundles(current=>current.map(item=>item.id===bundle.id?{...item,active:event.target.checked}:item))}/><i/></label></div><label>Made for<select value={bundle.recipientType} onChange={event=>setBundles(current=>current.map(item=>item.id===bundle.id?{...item,recipientType:event.target.value as Bundle["recipientType"]}:item))}><option>Lover</option><option>Friend</option><option>Parents</option><option>Sibling</option><option>Other</option></select></label><input className="admin-title-input" value={bundle.name} onChange={event=>setBundles(current=>current.map(item=>item.id===bundle.id?{...item,name:event.target.value}:item))}/><textarea value={bundle.description} onChange={event=>setBundles(current=>current.map(item=>item.id===bundle.id?{...item,description:event.target.value}:item))}/><label>Bundle price ₹<input type="number" value={bundle.pricePaise/100} onChange={event=>setBundles(current=>current.map(item=>item.id===bundle.id?{...item,pricePaise:Number(event.target.value)*100}:item))}/></label><button onClick={()=>saveBundle(bundle)}>Save bundle</button></article>)}</div></section>}
      {tab==="gifts"&&<DataTable title="All gifts" columns={["Gift","Recipient","Occasion","Value","Status"]} rows={gifts.map(gift=>[gift.title,gift.recipientName,gift.occasion,`₹${gift.totalPaise/100}`,gift.status])}/>}
      {tab==="orders"&&<DataTable title="Payments and orders" columns={["Order","Amount","Coupon","Status","Created"]} rows={orders.map(order=>[order.id.slice(0,8),`₹${order.amountPaise/100}`,order.couponCode||"—",order.status,new Date(order.createdAt).toLocaleDateString()])}/>}
      {tab==="users"&&<section className="admin-section"><div className="admin-section-head"><div><small>ACCOUNTS</small><h2>Users and roles</h2></div></div><div className="admin-table users"><div className="admin-table-row heading"><span>User</span><span>Email</span><span>Joined</span><span>Role</span><span>Access</span></div>{users.map(user=><div className="admin-table-row" key={user.id}><strong>{user.displayName||"mypookie user"}</strong><span>{user.email}</span><span>{new Date(user.createdAt).toLocaleDateString()}</span><span>{user.role}</span><select value={user.role} onChange={event=>updateRole(user,event.target.value)}><option>USER</option><option>ADMIN</option></select></div>)}</div></section>}
      {tab==="settings"&&overview&&<section className="admin-section"><div className="admin-section-head"><div><small>SYSTEMS</small><h2>Integration health</h2><p>Secrets stay server-side. This screen only shows connection readiness.</p></div></div><div className="integration-grid"><Integration name="Firebase Authentication" detail="Google sign-in and protected admin access" ready={overview.integrations.firebase}/><Integration name="Groq AI" detail="Playful quiz question generation" ready={overview.integrations.groq}/><Integration name="Razorpay" detail="Orders, Checkout and signature verification" ready={overview.integrations.razorpay}/><Integration name="Database" detail="Coupons, gifts, orders and responses" ready/></div></section>}
    </section>
  </main>;
}

function AdminOverview({data,gifts,orders}:{data:Overview;gifts:Gift[];orders:Order[]}){
  const metrics=[["Revenue",`₹${(data.revenuePaise/100).toLocaleString("en-IN")}`,"↗"],["Paid orders",String(data.paidOrders),"✓"],["Gifts created",String(data.gifts),"♡"],["Users",String(data.users),"◎"],["Responses",String(data.responses),"✦"],["Active coupons",String(data.activeCoupons),"%"]];
  return <><div className="admin-metrics">{metrics.map(metric=><article key={metric[0]}><span>{metric[2]}</span><small>{metric[0]}</small><strong>{metric[1]}</strong></article>)}</div><div className="admin-overview-grid"><DataTable title="Recent gifts" columns={["Gift","Recipient","Value","Status"]} rows={gifts.map(gift=>[gift.title,gift.recipientName,`₹${gift.totalPaise/100}`,gift.status])}/><DataTable title="Recent orders" columns={["Order","Amount","Coupon","Status"]} rows={orders.map(order=>[order.id.slice(0,8),`₹${order.amountPaise/100}`,order.couponCode||"—",order.status])}/></div></>;
}
function DataTable({title,columns,rows}:{title:string;columns:string[];rows:(string|number)[][]}){return <section className="admin-section data"><div className="admin-section-head"><div><small>LIVE DATA</small><h2>{title}</h2></div></div><div className="admin-data-table"><div style={{gridTemplateColumns:`repeat(${columns.length},minmax(110px,1fr))`}}>{columns.map(column=><strong key={column}>{column}</strong>)}</div>{rows.length?rows.map((row,index)=><div key={index} style={{gridTemplateColumns:`repeat(${columns.length},minmax(110px,1fr))`}}>{row.map((value,itemIndex)=><span key={itemIndex}>{value}</span>)}</div>):<p>No records yet.</p>}</div></section>}
function Integration({name,detail,ready}:{name:string;detail:string;ready:boolean}){return <article className="integration-card"><span className={ready?"ready":""}>{ready?"✓":"!"}</span><div><strong>{name}</strong><p>{detail}</p></div><b>{ready?"Connected":"Needs keys"}</b></article>}
