package com.mypookie.api.controller;
import com.fasterxml.jackson.databind.ObjectMapper; import com.mypookie.api.dto.InvitationRequest; import com.mypookie.api.dto.PaymentVerificationRequest; import com.mypookie.api.model.Invitation; import com.mypookie.api.repository.InvitationRepository; import com.mypookie.api.service.*;
import jakarta.validation.Valid; import lombok.RequiredArgsConstructor; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import org.springframework.web.server.ResponseStatusException; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/invitations") @RequiredArgsConstructor
public class InvitationController {
 private final InvitationRepository invitations; private final UserService users; private final RazorpayService razorpay; private final ObjectMapper json;
 @GetMapping public List<Invitation> mine(@AuthenticationPrincipal FirebaseAuthenticationFilter.UserPrincipal p){return invitations.findByCreatorIdOrderByUpdatedAtDesc(users.resolve(p).getId());}
 @PostMapping public Invitation create(@AuthenticationPrincipal FirebaseAuthenticationFilter.UserPrincipal p,@Valid @RequestBody InvitationRequest r){return save(users.resolve(p).getId(),null,r);}
 @PutMapping("/{id}") public Invitation update(@AuthenticationPrincipal FirebaseAuthenticationFilter.UserPrincipal p,@PathVariable String id,@Valid @RequestBody InvitationRequest r){return save(users.resolve(p).getId(),id,r);}
 @PostMapping("/{id}/payment-order") public Map<String,Object> paymentOrder(@AuthenticationPrincipal FirebaseAuthenticationFilter.UserPrincipal p,@PathVariable String id){var user=users.resolve(p);var invitation=owned(id,user.getId());if("PAID".equals(invitation.getPaymentStatus())&&invitation.getShareToken()!=null)return Map.of("paid",true,"shareToken",invitation.getShareToken());int amount=price(invitation);String orderId=razorpay.createOrder(amount,"INR","invite_"+invitation.getId().replace("-",""));invitation.setProviderOrderId(orderId);invitation.setAmountPaise(amount);invitation.setPaymentStatus("CREATED");invitation.setUpdatedAt(Instant.now());invitations.save(invitation);return Map.of("paid",false,"localInvitationId",invitation.getId(),"providerOrderId",orderId,"amountPaise",amount,"currency","INR","keyId",razorpay.keyId());}
 @PostMapping("/{id}/payment-verify") public Invitation verifyPayment(@AuthenticationPrincipal FirebaseAuthenticationFilter.UserPrincipal p,@PathVariable String id,@Valid @RequestBody PaymentVerificationRequest r){var user=users.resolve(p);var invitation=owned(id,user.getId());if("PAID".equals(invitation.getPaymentStatus())&&invitation.getShareToken()!=null)return invitation;if(!"CREATED".equals(invitation.getPaymentStatus())||!Objects.equals(invitation.getProviderOrderId(),r.razorpayOrderId())||!razorpay.verify(invitation.getProviderOrderId(),r.razorpayPaymentId(),r.razorpaySignature()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Payment verification failed.");invitation.setProviderPaymentId(r.razorpayPaymentId());invitation.setPaymentStatus("PAID");if(invitation.getShareToken()==null)invitation.setShareToken(UUID.randomUUID().toString().replace("-","").substring(0,24));invitation.setStatus("PUBLISHED");invitation.setUpdatedAt(Instant.now());return invitations.save(invitation);}
 @PostMapping("/{id}/publish") public Invitation publish(@AuthenticationPrincipal FirebaseAuthenticationFilter.UserPrincipal p,@PathVariable String id){var user=users.resolve(p);var invitation=owned(id,user.getId());if(!"PAID".equals(invitation.getPaymentStatus()))throw new ResponseStatusException(HttpStatus.PAYMENT_REQUIRED,"Complete payment before publishing.");return invitation;}
 private Invitation save(String userId,String id,InvitationRequest r){var invitation=id==null?new Invitation():owned(id,userId);if(id==null){invitation.setId(UUID.randomUUID().toString());invitation.setCreatorId(userId);invitation.setStatus("DRAFT");}else if("PAID".equals(invitation.getPaymentStatus()))throw new ResponseStatusException(HttpStatus.CONFLICT,"A published paid invitation cannot be edited.");invitation.setTitle(r.title().trim());invitation.setTradition(r.tradition().trim().toUpperCase());invitation.setDetailsJson(r.detailsJson());invitation.setUpdatedAt(Instant.now());return invitations.save(invitation);}
 private Invitation owned(String id,String userId){return invitations.findById(id).filter(value->value.getCreatorId().equals(userId)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Invitation not found."));}
 private int price(Invitation invitation){try{var details=json.readTree(invitation.getDetailsJson());int pages=1+details.path("events").size()+(details.path("showCountdown").asBoolean(false)?1:0);return 25100+Math.max(0,pages-7)*1000;}catch(Exception error){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Invitation details could not be priced.");}}
}
